# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Thehood', '0002_auto_20190707_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Thehood.Neighbourhood'),
        ),
    ]
