# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thehood', '0005_auto_20190708_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
